baseURL: http://example.org/
languageCode: en-us
title: "Toha"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true

# Enable Google Analytics
googleAnalytics: UA-xxxxxxxx

# Enable Disqus forum
disqusShortname: does-not-exist

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # copyright
  copyright: Â© 2020 Copyright.

  # background image of the landing page
  background: "images/background.jpg"

  # GitHub repo URL of your site
  gitRepo: https://github.com/hossainemruz/toha-example-site

  # specify whether you want to write blog post or not
  enableBlogPost: true

  # specify the list of custom menus that you want to show in the top navbar.
  # they will be separated by a divider from the main menus.
  customMenus:
  - name: Notes
    url: https://hossainnotes.netlify.app/docs/example/

  # some information about you
  author:
    name: "Jason Barnes"
    nickname: "NATS"
    image: "images/avatar-1.png"
    # give your some contact information. they will be used in the footer
    contactInfo:
      email: "barnes7599@gmail.com"
      phone: "(951)293-3849"
    # a summary of what you do
    summary:
    - Data Visualization
    - Data Analytics
    - Business Intelligence
